/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw02;

import org.apache.commons.cli.*;

public class App{
    public static void main(String[] args) {

    }
}
